In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [5]:
df=pd.read_csv("drug200.csv")

In [6]:
df.head(5)

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [7]:
#Encoding the categorical values to numericals
le=LabelEncoder()
df["Sex"]=le.fit_transform(df["Sex"])
df["BP"]=le.fit_transform(df["BP"])
df["Cholesterol"]=le.fit_transform(df["Cholesterol"])
df["Drug"]=le.fit_transform(df["Drug"])

In [8]:
df.head()

   Age  Sex  BP  Cholesterol  Na_to_K  Drug
0   23    0   0            0   25.355     0
1   47    1   1            0   13.093     3
2   47    1   1            0   10.114     3
3   28    0   2            0    7.798     4
4   61    0   1            0   18.043     0

In [9]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [17]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [18]:
X=df.drop("Drug",axis=1)
y=df["Drug"]

In [19]:
from sklearn.preprocessing import StandardScaler

In [ ]:
ss=StandardScaler()
X=ss.fit_transform(X)

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.